version: '3'

services:
  web:
    build:
      context: .
    platform: linux/amd64
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - .:/myapp #任意のアプリ名
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db

  db:
    platform: linux/x86_64 #M1チップ対応のため追記
    restart: always
    image: mysql:8
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  nginx:
    build:
      context: ./nginx
    platform: linux/amd64
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    depends_on:
      - web 

volumes:
  mysql-data: